version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 9000:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      DB_MONGO_USER: ${DB_MONGO_USER}
      DB_MONGO_PWD: ${DB_MONGO_PWD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes: 
      - ./mongo_team/mongo/init.d/:/docker-entrypoint-initdb.d/
      - ./mongo_team/mongo/data/:/data/db/
  
  mongo-express:
    depends_on:
      - mongo
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      DB_MONGO_USER: ${DB_MONGO_USER}
      DB_MONGO_PWD: ${DB_MONGO_PWD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/

  py_collection:
    build:
      context: ./fython
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3060:3060
      
  node_api:
    depends_on:
      - mongo
    build:
      context: ./node_commdb
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_USERNAME}
      DB_MONGO_USER: ${DB_MONGO_USER}
      DB_MONGO_PWD: ${DB_MONGO_PWD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      API_PORT: ${API_PORT}
      MONGO_PORT: ${MONGO_PORT}

  express_front:
    depends_on:
      - node_api
    build:
      context: ./express_dex
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    environment:
      API_PORT: ${API_PORT}
      API_ADDRESS: ${API_ADDRESS}
      PORT: ${EXP_PORT}
      PY_PORT: ${PY_PORT}
      PY_ADDRESS: ${PY_ADDRESS}
